### ISSUE TITLE
Not allowed characters in XMLs

### ISSUE THREAD

**Issue by jakubsikorski** [intel/Intel-PMT#4]
[Line 10 ](https://github.com/intel/Intel-PMT/blob/61602e7457804ee61db8c13d4f6ec26372023d15/xml/SPR/OOBMSM/CORE/spr_aggregator.xml#L10)of `SPR_aggregator.xml` contains an invalid character `&` `<TELC:DataTypesInclude>&otherfile;</TELC:DataTypesInclude>`

According to XML specification: `The ampersand character (&) and the left angle bracket (<) must not appear in their literal form`.

This is a security risk and should be fixed.

**Comment by joko-sastriawan** [comment]
Per XML specification, it is a valid entity reference. See: https://www.w3.org/TR/xml/#dt-entref 
Entity otherfile is defined as reference to spr_common.xml. Let me know if you are satisfied with this explanation.

**Comment by jakubsikorski** [comment]
It does, thanks
